name: Build/Deploy/Destroy Locust Service

on:
  push:
    branches:
      - stress_testing
    paths:
      - "locust/**"

  workflow_dispatch:
    inputs:
      action_type:
        description:
          "Do you want build new locust container or deploy/destroy a locust service? type \
          'build' to build new container, 'deploy' to deploy a locust service, 'destroy' to \
          destroy existing locust service. defaults to 'build' "
        required: true
        default: "build"

jobs:
  build:
    if: ${{github.event_name == "push" || github.event.inputs.action_type == 'build' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout files
        uses: actions/checkout@v2

      - name: Build and push locust
        id: docker_build_locust
        uses: docker/build-push-action@v2
        with:
          context: ./locust/
          file: ./locust/Dockerfile
          push: true
          tags: unstructuredstudio/zubhub-services_locust:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    if: ${{ github.event.inputs.action_type == 'deploy' }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy locust
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.DO_BACKEND_HOST }}
          USERNAME: ${{ secrets.DO_BACKEND_USERNAME }}
          KEY: ${{ secrets.DO_SSHKEY }}
          script: |
            docker service create --name zubhub-services_locust unstructuredstudio/zubhub-services_locust:latest \
              -p 8089:8089 -f /mnt/locust/locustfile.py

  destroy:
    if: ${{ github.event.inputs.action_type == 'destroy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Spawn down locust
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.DO_BACKEND_HOST }}
          USERNAME: ${{ secrets.DO_BACKEND_USERNAME }}
          KEY: ${{ secrets.DO_SSHKEY }}
          script: "docker service rm zubhub-services_locust"
