name: Scale Backend Deployment

on:
  workflow_dispatch:
    inputs:
      scaling_type:
        description: "Do you want to scale up or down? type either 'up' or 'down'. defaults to 'up'"
        required: true
        default: "up"

jobs:
  scale_up:
    if: ${{ github.event.inputs.scaling_type == 'up' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create new droplet
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
          run: doctl compute droplet list 'zubhub-services*' > /droplets.txt;droplets_count=`wc -l < /droplets.txt`;echo "INITIAL_DROPLETS_COUNT=$(($droplets_count-1))" >> $GITHUB_ENV;doctl compute droplet create zubhub-services-$INITIAL_DROPLETS_COUNT --snapshot $SOURCE_SNAPSHOT_ID --size s-1vcpu-1gb --region nyc1 --ssh-keys $DO_PUBLIC_SSHKEY_FP;echo "NEW_DROPLET_IP=$(doctl compute droplet get zubhub-services-$INITIAL_DROPLETS_COUNT --template "{{(index .Networks.V4 1).IPAddress}}")" >> $GITHUB_ENV

      - name: Connect new droplet to swarm
        uses: appleboy/ssh-action@master
        with:
          HOST: $NEW_DROPLET_IP
          USERNAME: ${{ secrets.DO_BACKEND_USERNAME }}
          KEY: ${{ secrets.DO_SSHKEY }}
          script: "docker swarm join --token ${{secrets.SWARM_WORKER_JOIN_TOKEN}} ${{secrets.SWARM_MASTER_HOST_AND_PORT}}"

      - name: Scale up deployment
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.DO_BACKEND_HOST }}
          USERNAME: ${{ secrets.DO_BACKEND_USERNAME }}
          KEY: ${{ secrets.DO_SSHKEY }}
          script: "docker service scale zubhub-services_web=$(($INITIAL_DROPLETS_COUNT+1))"

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: Copy file via scp
  #       uses: appleboy/scp-action@master
  #       env:
  #         HOST: ${{ secrets.DO_BACKEND_HOST }}
  #         USERNAME: ${{ secrets.DO_BACKEND_USERNAME }}
  #         KEY: ${{ secrets.DO_SSHKEY }}
  #       with:
  #         source: "."
  #         target: "/home/zubhub-services/zubhub"

  #     - name: Executing remote  command
  #       uses: appleboy/ssh-action@master
  #       with:
  #         HOST: ${{ secrets.DO_BACKEND_HOST }}
  #         USERNAME: ${{ secrets.DO_BACKEND_USERNAME }}
  #         KEY: ${{ secrets.DO_SSHKEY }}
  #         script: "cp /home/zubhub-services/zubhub/zubhub_backend/compose/deploy_backend.sh /home/zubhub-services/ && sudo bash /home/zubhub-services/deploy_backend.sh"
